name: DEV - CONTINUOUS INTEGRATIONS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: cypress run
        uses: cypress-io/github-action@v1
        with:
          env: true
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}