name: DEV - CONTINUOUS INTEGRATIONS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integrations:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: lint standard
        run: npm run lint:fix

      - name: cypress run
        uses: cypress-io/github-action@v1
       
      - name: generate and merge report
        run: npm run post-cy:run
        with:
          APP_URL: "https://serverest.dev"
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}